name: Test development environments

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-22.04, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[dev]"
      - name: Check all Makefile commands
        run: |
          make clean
          make lint
          make format
          make test
          make coverage
          make build
