name: CI

on: [pull_request]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        os: ["ubuntu-20.04", "windows-2019"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U pip wheel
          pip install -r requirements_dev.txt
      - name: Check linting
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test

# build:
#   on:
#     branches:
#       - main
#   runs-on: "ubuntu-20.04"
#   steps:
#   - uses: actions/checkout@v1
#     - name: Set up Python
#       uses: actions/setup-python@v1
#       with:
#         python-version: 3.9
#     - name: Install dependencies
#         run: |
#           pip install -U pip wheel
#           pip install -r requirements_dev.txt
#     - name: build wheel
#       run: |
#         make build
#     - name: Upload wheel
#       uses: actions/upload-artifact@v2
#       with:
#         name: wheel
#         path: dist/*.whl
